python scripts/solve_and_run_network.py with v1_k
python scripts/solve_and_run_network.py with v2_k
python scripts/solve_and_run_network.py with v3_k
python scripts/solve_and_run_network.py with v4_k
python scripts/solve_and_run_network.py with v1_bst
python scripts/solve_and_run_network.py with v2_bst
python scripts/solve_and_run_network.py with v3_bst
python scripts/solve_and_run_network.py with v4_bst
python scripts/solve_and_run_network.py with bevconv_bst
python scripts/solve_and_run_network.py with bevformer_bst
