model: "data/net_perf/bst_comm/inception_resnet_v2_detail_comm.csv"
subgraph: "third_party/Partitioning-Algorithm/mapping_strategy/subgraphs/bst/InceptionResnetV2_bst.csv"
chip_id: "bst"
dump_path: "results/pipeline/bst/inception_resnet_v2_pipeline"
